database:
  url: sqlite+aiosqlite:///./data/database.db

scheduling:
  url: sqlite:///./data/database.db

scripting: {}

auth:
  jwt:
    secret_key: $auth.jwt.secret_key
    algorithm: HS256
    expire_minutes: 30
  hasher:
    schemas: bcrypt
  service:
    enabled: true
    password: rpass

icoms:
  icoms:
    main:
      name: "Главный"
      direct: true

roles:
  init: true
  roles:
    user:
      - bmaster.icoms.read
      - bmaster.sounds.manage
      - bmaster.icoms.queue.manage
      - bmaster.icoms.queries.audio
      - bmaster.icoms.queries.sound
      - bmaster.icoms.queries.stream
      - school.manage

    admin:
      - bmaster.icoms.read
      - bmaster.sounds.manage
      - bmaster.icoms.queue.manage
      - bmaster.icoms.queries.audio
      - bmaster.icoms.queries.sound
      - bmaster.icoms.queries.stream
      - school.manage

      - bmaster.accounts.manage
      - bmaster.roles.manage
      - bmaster.scripting.manage
